name: Gradle CI Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Gradle Build
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: curl endpoint
        run: curl https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.12%2B7/OpenJDK17U-jdk_x64_linux_hotspot_17.0.12_7.tar.gz
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

#      - name: Setup Testcontainers Cloud Client
#        uses: atomicjar/testcontainers-cloud-setup-action@main
#        with:
#          token: ${{ secrets.TC_CLOUD_TOKEN }}

      - name: Build with Gradle
        run: ./gradlew build

